name: 'Release chef'
description: 'Release cookbook'
runs:
  using: "composite"
  steps: 
    - name: Create Chef .pem file
      id: pem
      env:
        PEM: ${{ secrets.PEM_BASE64 }}
      run: echo $PEM | base64 --decode > newrelic.pem
      shell: bash  
    - name: Release
      id: release
      run: rm -rf cookbooks/* && berks vendor cookbooks && knife supermarket share newrelic-infra
      shell: bash
