on: [push]

jobs:
  install_chef_job:
    runs-on: ubuntu-latest
    name: Chef workstation installation
    steps:
      - uses: actions/checkout@v2
      - name: Install Chef Workstation
        uses: ./.github/actions/install.yml
        with:
          version: "21.2.278"
