on: [push]

jobs:
  install_chef_job:
    runs-on: ubuntu-latest
    name: Chef workstation installation
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - name: Run action
      - uses: newrelic/infrastructure-agent-chef@github-actions
        with:
          version: "21.2.278"
