on: [push]
name: Chef workflow

jobs:
  install_chef_workstation:
    runs-on: ubuntu-latest
    name: Chef Workstation installation
    steps:
      - uses: actions/checkout@v2
      - name: Install Chef Workstation
        uses: newrelic/infrastructure-agent-chef/.github/actions/installation@github-actions
        with:
          version: "21.2.278"
      - name: Run tests
        uses: newrelic/infrastructure-agent-chef/.github/actions/tests@github-actions
