on:
  release:
    types: [published]
name: Release workflow

jobs:
  release-chef:
    runs-on: ubuntu-latest
    name: Install chef and run tests
    steps:
      - uses: actions/checkout@v2
      - name: Install Chef Workstation
        uses: newrelic/infrastructure-agent-chef/.github/actions/installation@master
      - name: Run linter
        uses: newrelic/infrastructure-agent-chef/.github/actions/linter@master
      - name: Run tests
        uses: newrelic/infrastructure-agent-chef/.github/actions/tests@master
      - name: Release
        uses: newrelic/infrastructure-agent-chef/.github/actions/release@master
        with:
          chef_pem_file: ${{ secrets.PEM_BASE64 }}        
